first_project/first_app/urls.py
from django.conf.urls import include
from first_app import views
from django.urls import path

#TEMPLATE TAGGING

app_name = 'first_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views



urlpatterns = [
    path('',views.index,name='index'),
    path("admin/", admin.site.urls),
    path('first_app/',include('first_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

    
class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

# Model for User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username


    

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfielnfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')




    

    

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse 
from first_app.models import Topic,Webpage,AccessRecord
from first_app.forms import UserForm,UserProfielnfoForm

from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':1000}
    return render(request,"first_app/index.html",context_dict)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfielnfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfielnfoForm()

    return render(request,'first_app/registration.html',
                            {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered})
            

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password: {} ".format(username,password))
            return HttpResponse("Invalid login crediantial!")
    
    else:
        return render(request,'first_app/login.html',{})



def relative(request):
    return render(request,'first_app/relative_url_template.html')

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:register' %}">Register</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:user_login' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Other</a>
            </li>
          </ul>

        </div>
      </nav>

    <div class="container">
        {% block body_block %}
        <!-- comment -->

        {% endblock %}
    </div>
    
</body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %} 
    {% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to Index Page</h1>
        <h2>This is showing home page</h2>
        <h1>{{ text|cut:'world' }}</h1>
        <h1>{{ number }}</h1>
    </div>
    {% endblock %}

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
    {% block body_block %}

<div class="jumbotron">
    <h1> Please Login</h1>
    <form action="{% url 'first_app:user_login' %}" method="POST" >
        {% csrf_token %}
        <label for="username"> UserName: </label>
        <input type="text" name="username" id="" placeholder="Enter Username">

        <label for="password"> Password: </label>
        <input type="password" name="password" id="">

        <input type="submit" name="" id="" value="Login">
    </form>
</div>
    {% endblock %}

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
    {% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank u for registering!</h1>
        {% else %}
            <h2>Register Here</h2>
            <h3>Fill out the form </h3>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" id="" value="Register " >
            </form>
        {% endif %}
    </div>
        
    {% endblock %} 

first_project/templates/first_app/relative_url_template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative URL template</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1> Welcome to relative url templates</h1>
            <a href="{% url 'first_app:other' %}"> The other page</a>
        </div>
    </div>
    
    
</body>
</html>